# Generated by Django 3.0.3 on 2020-06-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulli', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=60)),
                ('qmimi', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
