# Generated by Django 3.0.7 on 2020-06-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0004_auto_20200604_2256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='card',
            new_name='Test',
        ),
    ]
