# Generated by Django 3.0.7 on 2020-06-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0005_auto_20200608_0008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Card',
        ),
    ]
