# Generated by Django 3.0.7 on 2020-06-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0007_card_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='foto',
            field=models.ImageField(upload_to='media', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='card',
            name='qmimi',
            field=models.IntegerField(blank=True),
        ),
    ]
