# Generated by Django 3.0.7 on 2020-06-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0009_auto_20200609_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
